README.md
RNYamap.podspec
android/build.gradle
android/src/main/java/ru/vvdev/yamap/RNYamapManager.java
android/src/main/java/ru/vvdev/yamap/RNYamapModule.java
android/src/main/java/ru/vvdev/yamap/RNYamapPackage.java
android/src/main/java/ru/vvdev/yamap/YaMapView.java
index.d.ts
ios/RCTConvert+Yamap.m
ios/RNYMView.h
ios/RNYamap.h
ios/RNYamap.m
ios/RNYamap.xcodeproj/project.pbxproj
ios/YamapView.h
ios/YamapView.m

>Android
+ MasstransitRouter implementation
+ null-safety for ImageProvider (empty default constructor and null-checking)
+ PedestrianRouter implementation
>iOS
+ YMKMasstransitRouter/YMKPedestrianRouter implementation
+ onMarkerPress method refactoring
+ safe icons setting
> userLocation arrow icon is appended
> route's colors are passed through
> readme updates

Routing API's implementation

---

README.md
RNYamap.podspec
android/build.gradle
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/utils/RouteManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
index.d.ts
ios/RNYamap.m
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
package.json
src/components/Yamap.js
src/geocoding/index.js
src/utils/CallbacksManager.js
src/utils/index.js

Реализованы следующие роутеры:
- **masstransit** - для маршрутов на общественном транспорте
- **pedestrian** - для пешеходных маршрутов
- **driving** - для маршрутов на автомобиле 
Обновлена документация

Реализация апи для маршрутов

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
index.d.ts
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
package.json
src/components/Yamap.js

добавил параметр `showUserPosition` позволяющий скрыть положение пользователя.
Для обратной совместимости значение по умолчанию `true`
Обновлена документация и типы для typescript

добавил пропс showUserPosition

---

README.md
android/src/main/java/ru/vvdev/yamap/view/YamapMarker.java
ios/View/YamapMarkerView.m
package.json

- исправлена установка для проектов без typescript
- фиксы падений на андроид и ios

Версия 1.0.15

---

README.md
android/src/main/java/ru/vvdev/yamap/RNYamapModule.java
ios/RNYamap.m
package.json
src/components/Yamap.tsx

Методы из sdk:
- setLocale
- getLocale
- resetLocale

Возможность смены локализации карт

---

README.md
android/src/main/java/ru/vvdev/yamap/RNYamapModule.java
android/src/main/java/ru/vvdev/yamap/RNYamapPackage.java
android/src/main/java/ru/vvdev/yamap/YamapCircleManager.java
android/src/main/java/ru/vvdev/yamap/YamapMarkerManager.java
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapCircle.java
android/src/main/java/ru/vvdev/yamap/view/YamapMarker.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/RNYamap.m
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/View/YamapCircleView.h
ios/View/YamapCircleView.m
ios/View/YamapMarkerView.m
ios/YamapCircle.h
ios/YamapCircle.m
ios/YamapView.m
package.json
src/components/Circle.tsx
src/components/Polygon.tsx
src/components/Yamap.tsx
src/index.ts
src/interfaces.ts

- Исправлены предупреждения компилятора в XCode
- Добавлен примитив Circle
- Обновлен метод setCenter. Реализована параметризация анимации и углов азимута и наклона
- Исправлены проблемы с локализацией на ios
- Небольшой рефакторинг и чистка кода

Версия 1.0.17

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapMarkerManager.java
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapMarker.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/View/YamapMarkerView.h
ios/View/YamapMarkerView.m
ios/YamapMarker.m
ios/YamapView.m
package.json
src/components/Circle.tsx
src/components/Marker.tsx
src/components/Polygon.tsx
src/components/Polyline.tsx
src/components/Yamap.tsx
src/interfaces.ts

- mapStyle
- nightMode
- anchor для компонента Marker
- методы setZoom, getCameraPosition и параметр onCameraPositionChange
- кастомизация UserLocationAccuracyCircle

Версия 1.0.18

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapMarkerManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapMarker.java
ios/View/YamapMarkerView.h
ios/View/YamapMarkerView.m
ios/YamapMarker.m
package-lock.json
package.json
src/components/Marker.tsx

- Добавлен новый prop `visible` для компонента `Marker`
- Исправлена ошибка `weak_ptr` на Android по issue #102
- Уменьшено время задержи перерисовки маркеров на iOS (улучшения согласно [документации](https://developer.apple.com/documentation/dispatch/1452876-dispatch_after))

Новый prop для маркера, улучшения на iOS, исправления на Android

---

ios/View/RNYMView.m
ios/View/YamapMarkerView.m
package-lock.json
package.json

- Оказалось что функции `isValid()` нет в iOS, зато есть `valid`, но относящаяся к другому классу (неизвестно что кого наследует из их документации по iOS) ([документация](https://yandex.ru/dev/maps/archive/doc/mapkit/3.0/concepts/ios/mapkit/ref/YMKMapObject.html#property_detail__property_valid));
- Исправлена сборка на iOS;
- Исправлены названия переменной в функции очистке объекта (на работоспособность никак не влияло).

Исправлена ошибка сборки на iOS

---

src/geocoding/index.ts

Исправил отправку центра области поиска. Просьба не судить строго. Первый раз правку предлагаю...

fix: added center search area

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/View/RNYMView.m
ios/YamapView.m
package-lock.json
package.json
src/components/Yamap.tsx
src/interfaces.ts

- Добавлена возможность включать/отключать задержку в 300мс при нажатии [fastTapEnabled](https://github.com/volga-volga/react-native-yamap/commit/b19bd252f0414f8bc8a0414f4fcb0b975bf8f199)
- Добавлена возможность определять тип подложки карты [map type](https://github.com/volga-volga/react-native-yamap/commit/183e9bd84b9ae2129b218a887f3e37cd0c098424)

New props for mapType and fastTapEnabled

---

android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
package-lock.json
package.json

- Добавлен `reason` в колбек `onCameraPositionChange`

Изменения согласано замечаниями и reason в колбеке

---

ios/View/RNYMView.m
ios/YamapView.m

- Удалена тестовая функция вызывавшая ошибку при сборке приложения

Исправлена сборка на iOS

---

ios/View/RNYMView.m

Исправил вместимость кластеризатора, теперь количество маркеров в кластере 99+ отображаются корректно.

Вместимость кластеризатора

---

src/components/Yamap.tsx

- fix: fixed wrong initialRegion params in React.

Fixed broken initialRegion

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
src/components/Yamap.tsx
src/index.ts

- Implemented ref `setTrafficVisible` for iOS;
#84 
- Implemented prop `interactive` for iOS/Android;
#47 
- Implemented prop `maxFps` for iOS/Android;
- README.md update;
- Code style update.

Bunch of new props/refs

---

README.md
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/Converter/RCTConvert+Yamap.m
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
src/components/Yamap.tsx
src/interfaces.ts

- Implemented `getWorldPoints` ref to get world coordinates from `[{ x, y }, ...]` of screen;
- Implemented `getScreenPoints` ref to get screen coordinates from `[{ lat, lon }, ...]` of marker;
- Fixed missing default `maxFps` value;
#82 
#44
- README.md update.

New `getWorldPoints` and `getScreenPoints`

---

src/components/Yamap.tsx

- Fixed returning data for `getCameraPosition`, `findRoutes`, `findMasstransitRoutes`, `findPedestrianRoutes` and `findDrivingRoutes`;
#169 
- Code style changes.

Updated callback data

---

README.md
android/src/main/java/ru/vvdev/yamap/ClusteredYamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/ClusteredYamapView.m
ios/View/RNYMView.h
ios/View/RNYMView.m
src/components/ClusteredYamap.tsx
src/components/Yamap.tsx

add props "followUser" to MapView that add camera anchor with autoZoom, heading.

Add follow user props

---

ios/YamapSuggests.m

Creating search manager not in main thread causes suggest to resolve never

Fix suggest get stuck on iOS

---

README.md
android/src/main/java/ru/vvdev/yamap/ClusteredYamapViewManager.java
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/ClusteredYamapView.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/View/RNCYMView.h
ios/View/RNCYMView.m
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/YamapView.m
src/components/ClusteredYamap.tsx
src/components/Yamap.tsx
src/interfaces.ts

- Added prop `logoPosition`.
#180

New prop `logoPosition`

---

README.md
android/src/main/java/ru/vvdev/yamap/ClusteredYamapViewManager.java
android/src/main/java/ru/vvdev/yamap/YamapViewManager.java
android/src/main/java/ru/vvdev/yamap/view/YamapView.java
ios/ClusteredYamapView.m
ios/View/RNYMView.h
ios/View/RNYMView.m
ios/View/YamapMarkerView.h
ios/YamapView.m
src/components/ClusteredYamap.tsx
src/components/Yamap.tsx
src/interfaces.ts

- Added prop to control userPosition image with scaling;
#189

New prop for user image scaling

---

ios/View/YamapMarkerView.m
ios/YamapMarker.m

https://github.com/volga-volga/react-native-yamap/issues/206

fix: issue crash ios - added try-catch for animated methods

---

android/src/main/java/ru/vvdev/yamap/view/ClusteredYamapView.kt

fix: add non-null checks (ClusteredYamapView)
